### ISSUE TITLE
Error Message: You need the latest Java Runtime Environment

### ISSUE THREAD

**Issue by geoffrothman** [solarkennedy/ipmi-kvm-docker#11]
When I go to my ipmi's ip address to view my actual console screen, it says "You need the latest Java Runtime Environment. Would you like to update now?" Ok or Cancel...I click Ok and nothing happens.

![javaissue](https://user-images.githubusercontent.com/4984045/107533007-1c532c00-6b84-11eb-9145-99d3c3d90455.png)

**Comment by TokugawaHeavyIndustries** [comment]
Hey Geoff, that's normal.  Just click cancel.  The launch.jnlp that downloaded is what you'll want to open.  Use the default app handler.
