### ISSUE TITLE
no iKVM64 in java.library.path

### ISSUE THREAD

**Issue by geigeralex** [solarkennedy/ipmi-kvm-docker#14]
Hello, did you get the image work on the apple m1 silicon chips? I used Dockerfile.arm64 to build the docker image,  but I'm getting the error no iKVM64 in java.library.path.
 
![no_iKVM64](https://user-images.githubusercontent.com/87528372/125942292-14d6e4a6-de9a-4720-b705-fee6914fdf44.jpg)

**Comment by geigeralex** [comment]
closed.

**Comment by luborjurena** [comment]
Have you found solution?

**Comment by lanrat** [comment]
How was this fixed? I'm getting the same error.

<img width="987" height="467" alt="Image" src="https://github.com/user-attachments/assets/b465bf06-4af6-454b-8d27-f340a8c663cd" />

**Comment by Jeff-liaojinfu** [comment]
您的邮件我已经收到，我会尽快回复您！
