### ISSUE TITLE
xdg-open on mac

### ISSUE THREAD

**Issue by axlroden** [solarkennedy/ipmi-kvm-docker#16]
On mac .. if you dont want to install all kinds of things.. 
`open http://127.0.0.1:8080` works, would be nice with a little comment about that, as I went on a google spree to get xdg, until I found out i can just type open.

**Comment by axlroden** [comment]
Also.. 
[program:chromium]
command=/usr/bin/chromium-browser --no-sandbox -test-type --window-position=0,0 --window-size=1024,722
autorestart=true

Having this in supervisor.conf makes the chrome browser stop warning about sandbox, and have perfect size for chrome at 1024x768

Currently if you leave the sandbox warning the download bar is obstructed.

**Comment by solarkennedy** [comment]
Can you make a PR?

**Comment by axlroden** [comment]
#17 
Done
