### ISSUE TITLE
Java crash on HP DL360G5 ILO

### ISSUE THREAD

**Issue by Mebus** [solarkennedy/ipmi-kvm-docker#2]
Hallo,

we just tried this on a HP DL360G5, but Java crashes with the following error:

![Screenshot_20200704_200756](https://user-images.githubusercontent.com/271557/86518410-3381ac80-be32-11ea-8fcd-fbcbc9b04804.png)

Do you know how to fix this?

Mebus

**Comment by solarkennedy** [comment]
Hmm. Not sure.
I think it is super likely that this version of iLO requires a specific version of java.

The stock image comes with a super old version (7) on purpose:
https://github.com/solarkennedy/ipmi-kvm-docker/blob/b932d5758272d4f7ca7ed14caa2081a380b78078/Dockerfile#L7

Maybe it needs a newer one? Or heck an even older one?

**Comment by TokugawaHeavyIndustries** [comment]
Hey @Mebus , it appears that HP has a firmware update for iLO2 to support Java 7 (that this project uses).  Can you try this and report back? https://support.hpe.com/hpesc/public/docDisplay?docId=c04818378
