### ISSUE TITLE
Recreation of this container for ARM?

### ISSUE THREAD

**Issue by Plaidstallion** [solarkennedy/ipmi-kvm-docker#3]
I would like to set this container up on a Raspberry Pi4 and was hoping someone with the know-how could recreate this image to work with ARM based processors.

**Comment by TokugawaHeavyIndustries** [comment]
Working on this, @Plaidstallion

**Comment by Plaidstallion** [comment]
Looking forward to hear more. Thanks!

**Comment by TokugawaHeavyIndustries** [comment]
Hey @Plaidstallion I just pushed an update for armhf.

Try it out for me:

```
docker build -f ./Dockerfile.armhf -t ipmi-kvm-docker:armhf .
docker run -p 8080:8080 ipmi-kvm-docker:armhf
```

Note this version uses Chrome rather than Firefox.

**Comment by Plaidstallion** [comment]
```
...Unpacking gconf2-common (3.2.6-0ubuntu2) ...
dpkg: error processing archive chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
dpkg: error processing archive gconf-service_3.2.6-0ubuntu2_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
dpkg: error processing archive chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
Setting up gconf2-common (3.2.6-0ubuntu2) ...

Creating config file /etc/gconf/2/path with new version
Errors were encountered while processing:
 gconf-service-backend_3.2.6-0ubuntu2_armhf.deb
 libgconf-2-4_3.2.6-0ubuntu2_armhf.deb
 chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb
 gconf-service_3.2.6-0ubuntu2_armhf.deb
 chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb
The command '/bin/sh -c dpkg -i gconf-service-backend_3.2.6-0ubuntu2_armhf.deb libgconf-2-4_3.2.6-0ubuntu2_armhf.deb gconf2-common_3.2.6-0ubuntu2_all.deb chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb gconf-service_3.2.6-0ubuntu2_armhf.deb chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb' returned a non-zero code: 1
:~/docker/ipmi-kvm-docker$ docker run -p 8080:8080 ipmi-kvm-docker:armhf
Unable to find image 'ipmi-kvm-docker:armhf' locally
docker: Error response from daemon: pull access denied for ipmi-kvm-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

This was the end of the build and trying to run the docker. I'm sorry that I can't really offer much insight as to what is wrong. There were some errors before this too.

**Comment by solarkennedy** [comment]
Looks like you are on an `arm64` system. This build is intended for `armf`.

**Comment by TokugawaHeavyIndustries** [comment]
Yup, that's it.  I just added an `arm64` dockerfile, give it a shot @Plaidstallion 

```
docker build -f ./Dockerfile.arm64 -t ipmi-kvm-docker:arm64 .
docker run -p 8080:8080 ipmi-kvm-docker:arm64
```

**Comment by Plaidstallion** [comment]
![image](https://user-images.githubusercontent.com/44079566/97632263-91b24b00-1a32-11eb-9de5-49dbef5350db.png)

Getting closer! Do I need to define any volume mounts to change any variables? The window disappears after trying to connect to video. I allowed pop ups in the top right corner too.

**Comment by TokugawaHeavyIndustries** [comment]
Expand that window a bit and there should be a downloaded .jnlp file that you can click on and run.  It should already have java prefilled in the "run with" window.

**Comment by Plaidstallion** [comment]
Ah yes, sorry. After clicking on the .jnlp file A program called Iced Tea shows a splash screen and then the following error is displayed.

![image](https://user-images.githubusercontent.com/44079566/97632920-87448100-1a33-11eb-868b-7d5b9d4a202d.png)

I have two devices with the IPMI. On one I am left with a window showing a black background in the console viewer. The other I am left looking at the downloads pane in the browser after closing the error message

**Comment by TokugawaHeavyIndustries** [comment]
Yeah IcedTea is the Java implementation that this project uses.  Can you hit Show Details and paste the log in here?  I only have one legacy IMPI KVM device (a Supermicro board) and it works okay with `arm64` but I do see Megarac in your last screenshot...  Unfortunately I just got rid of a machine with a Megarac BMC 🤕

**Comment by Plaidstallion** [comment]
![image](https://user-images.githubusercontent.com/44079566/97634751-8c56ff80-1a36-11eb-9363-9600e3c2d6c9.png)
Sorry for the janky screen capture. I couldn't figure out a way to copy and paste from the VNC session. Is this ok? I am off to bed but I will check first thing in the morning. I am very interested in this. Thanks for doing it.

**Comment by TokugawaHeavyIndustries** [comment]
Just pushed a new update to Dockerfile.arm64 and a new file you'll need (deployment.properties).  Try rebuilding the image and we'll see if that fixes it!

**Comment by Plaidstallion** [comment]
I did a `git clone` and then `docker build -f ./Dockerfile.arm64 --no-cache -t ipmi-kvm-docker:arm64 .` Looks to be the same error.

edit: but I am seeing this inside the container

```
root@e2713d2437ff:~# cd .java/deployment
bash: cd: .java/deployment: No such file or directory
```

I will make a volume mount for that folder and add the file with `deployment.security.level=ALLOW_UNSIGNED` inside to see what happens.

---- I mapped the folder and can see it at `:~# less /root/.java/deployment/deployment.properties` inside the container and get the same error. It must be looking for it somewhere else. I will keep playing with it.

---- I see you placed that file inside a directory for iced tea

```:~# find / -name "deployment.properties"
/root/.config/icedtea-web/deployment.properties
/root/.java/deployment/deployment.properties
```

And it shows 
```:~# less /root/.config/icedtea-web/deployment.properties
deployment.security.level=ALLOW_UNSIGNED
```

**Comment by Plaidstallion** [comment]
Ok so I made some progress. Based on this blog post [here](https://techblog.jeppson.org/2018/01/fix-icedtea-cannot-grant-permissions-unsigned-jars-error/) I made a change to `/etc/java-7-openjdk/security/java.security`:

```
jdk.jar.disabledAlgorithms=MD2, MD5, RSA keySize < 1024

--->

jdk.jar.disabledAlgorithms=MD2, RSA keySize < 1024
```

I did it just by copying the file outside the container, making the change to the text file and then mapping to it in docker volume mounts though. I'm sure you know how to edit the file inside the container.

I can now open the viewer after several prompts warning me of unsecure settings but the last part where it refreshes to actually show what is going on in the console does not occur. In the screen shot below the console is shown on the left for your arm64 container and on the right for the solarkennedy x86 container

![image](https://user-images.githubusercontent.com/44079566/97693836-053f7100-1aa2-11eb-93a4-8a4681c714a5.png)

edit:

I tried it on my other Asus board that also has a Megarac BMC and I get this different error. The first system has the ASMB7-iKVM and this other has the ASMB8-iKVM. Again, both show the console in the solarkennedy image:

![image](https://user-images.githubusercontent.com/44079566/97696183-7b91a280-1aa5-11eb-8155-5c52d4ae55f5.png)
 Possibly the [version](https://github.com/AdoptOpenJDK/IcedTea-Web/issues/324) of IcedTea-web needs to be updated?

**Comment by TokugawaHeavyIndustries** [comment]
So, how the JNLPs work is they actually detect the architecture and serve different jars for each arch.  My guess is, the `arm64` arch is throwing off the BMC and they don't know what to load.  I can reproduce this with my Supermicro board - it works on `armhf` but not `arm64`.  Do you have the capability to test the `armhf` build?

I think for `arm64` we're probably SOL unless we can rebuild and run under qemu.  I'll take a look at this later today.

**Comment by Plaidstallion** [comment]
I have a raspberry pi original model B with raspbian on it. I know that thing takes forever to spin up docker containers but maybe worth a shot? I am assuming there is no way to run the armhf build on the pi4? It's on Ubuntu 20.04 if that matters.

**Comment by TokugawaHeavyIndustries** [comment]
You can definitely run armhf on Pi4, just need a 32-bit OS.  It should work on the original Pi, too!

**Comment by Plaidstallion** [comment]
Ah ok. I will have to take down my pihole instance and dig up another sd card to load the 32bit OS. I will report back if I have any luck.

**Comment by TokugawaHeavyIndustries** [comment]
Note - arm builds are 32-bit only at the moment
