### ISSUE TITLE
Readme cleanup and additions for new architectures

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [solarkennedy/ipmi-kvm-docker#7]
Hey @solarkennedy are you okay with it if I cleanup the readme and add some more instructions for additional architectures?  I just added armhf and I'd like to add arm64 in the near future.

Also, the Docker Hub build needs to be updated to the latest commits 😄 I can do that too if you'd like.

**Comment by solarkennedy** [comment]
Go for it!
You are a contributor, no need to even PR if you don't want to :)

**Comment by TokugawaHeavyIndustries** [comment]
Does Docker Hub have a rights/permission feature like GitHub does?

**Comment by solarkennedy** [comment]
Yep! Just give me your docker hub username and I'll add you to the repo.
I enabled automatic builds just now. They have been off for the last... 5 years

**Comment by TokugawaHeavyIndustries** [comment]
Same as here - tokugawaheavyindustries 👍

**Comment by solarkennedy** [comment]
Added.

Commit or PR at will.
